# Generated by Django 3.0.6 on 2020-05-27 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_internships'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Internships',
            new_name='Internship',
        ),
    ]
